Ap 4628 - adding offline order for Magento.
apruve/apruve-magento pull request #5
Opened 2017-01-30 18:01 UTC by Pro777

2017-01-30 19:29 UTC, CullenShane commented on app/code/community/Apruve/ApruvePayment/Model/Api/Rest/Account.php
> +            if ($buyer['email'] === $email) {
emails from Apruve should be downcased, is this comparison case insensitive or downcased to match?

2017-01-30 19:34 UTC, CullenShane commented
There's also a number of files that changed from 755 to 644 permissions.  Is there any reason for that change?

2017-01-30 19:59 UTC, Pro777 commented
@CullenShane I'll fix those permissions issue.

2017-01-30 20:29 UTC, CullenShane approved these changes
:work_on_my_machine:

:man_shrugging: Looks ok to me!

2017-01-30 20:31 UTC, donnen requested changes

2017-01-30 20:31 UTC, donnen commented on app/code/community/Apruve/ApruvePayment/Model/Api/Rest/Order.php
> +        if ($shopper_id) {
What happens when the $shopper_id is not found?

2017-01-30 21:06 UTC, Pro777 commented on app/code/community/Apruve/ApruvePayment/Model/Api/Rest/Order.php
> +        if ($shopper_id) {
Ok, I added code in the getShopperId method which will throw an exception if a shopper's email address is not found.

2017-01-30 21:24 UTC, donnen commented on app/code/community/Apruve/ApruvePayment/Model/Api/Rest/Order.php
> +        if ($shopper_id) {
Okay, we just need to let the merchant know that they can't check out using Apruve if the buyer doesn't have an account.

2017-02-08 16:03 UTC, CullenShane commented
Does the version of the plugin need to be updated?

2017-02-10 17:18 UTC, merged